# Generated by Django 4.2.1 on 2023-05-13 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Celular')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('avatar', sorl.thumbnail.fields.ImageField(blank=True, height_field='height_avatar', upload_to='avatars', verbose_name='Avatar', width_field='width_avatar')),
                ('width_avatar', models.PositiveIntegerField(blank=True, null=True)),
                ('height_avatar', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
