# Generated by Django 4.2.1 on 2023-05-16 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('plate', models.CharField(help_text='Escreva a placa no formato: XXXXXXX', max_length=7, primary_key=True, serialize=False, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.CharField(max_length=4, verbose_name='Ano')),
                ('rented', models.BooleanField(verbose_name='Alugado')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, height_field='height_image', upload_to='cars', verbose_name='Imagem', width_field='width_image')),
                ('width_image', models.PositiveIntegerField(blank=True, null=True)),
                ('height_image', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('rental_number', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=6, lowercase=True, unique=True, verbose_name='Codigo')),
                ('rent_date', models.DateField(verbose_name='Data de aluguel')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Data de devolução')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rents', to='aluguel.car', verbose_name='Carro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rents', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
