# Generated by Django 4.2.1 on 2023-05-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Aluguel', 'verbose_name_plural': 'Alugueis'},
        ),
        migrations.AlterField(
            model_name='car',
            name='rented',
            field=models.BooleanField(default=False, verbose_name='Alugado'),
        ),
    ]
