# Generated by Django 4.2.1 on 2023-05-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_alter_car_options_alter_rent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
