# Generated by Django 4.2.1 on 2023-05-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0003_rent_rent_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='rent_amount',
        ),
        migrations.AddField(
            model_name='car',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor'),
        ),
    ]
