# Generated by Django 4.2.1 on 2023-05-18 14:06

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0004_remove_rent_rent_amount_car_rent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='concluded',
            field=models.BooleanField(default=False, verbose_name='Concluido'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Diária'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rental_number',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=6, unique=True, uppercase=True, verbose_name='Codigo'),
        ),
    ]
